# Site settings
title: Pride In Microbiology
email: prideinmicrobiology@gmail.com
url: https://prideinmicrobiology.github.io
description: ""
keywords: ""
skills: "Professional Development - Mentorship - Community"
meta_author: Getz Landon

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d8dee9 #18bc9c #80B3FF
  primary-rgb: "216, 222, 233" #"24,288,156" #"128,179,255"
  secondary: 5e81ac #FD6E8A
  secondary-dark: 4c566a #A2122F

# Footer settings
footer:
  copyright: Pride in Microbiology
  location: Co-Founders of the Network
  social: Around the Web
  credits: Website Acknowledgements

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/prideinmicro



# Postal address (add as many lines as necessary)
address:
  - line: Dr. Landon J. Getz, PhD
  - line: Dr. Edel Pérez-López, PhD
  - line: Dr. Bruno Francesco Rodrigues de Oliveira, PhD

# Credits content

credits: 'The Pride in Microbiology logo was designed by Karina Gisèle Mac Si Hone. This website is based on the Freelancer theme, a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: "/profiles"
      type: "posts"
    values:
      permalink: ""
